### ISSUE TITLE
DAeC-Index für Ventus 2a

### ISSUE THREAD

**Issue by charlie-bauder** [weglide/GliderList#15]
Hi,
bis jetzt ist der Ventus 2a in der DAeC-Liste mit Index 114 gelistet, und nicht mit 110
Gruß
Charlie

**Comment by moldhouse** [comment]
Ventus 2a is listed with index of 114 in GliderList. It appears you have selected Ventus 15m on some of your WeGlide flights.

**Comment by charlie-bauder** [comment]
no, I uploaded a .igc-file, flewn an declared with my ventus 2a. 
The points where counted with index 110 instead of 114. 
So the software didn't read the wright glider from the logfile.

**Comment by moldhouse** [comment]
Thanks for reporting. This is however not an issue with a wrong index in GliderList but rather that we read the wrong aircraft from the file. Your file states 'Ventus2AX/15m' as glider type. I will have a look at how we can improve on reading the right glider. In the meantime, you can also change the glider in the flight settings.
