### ISSUE TITLE
Type and class

### ISSUE THREAD

**Issue by RosscoW** [weglide/GliderList#27]
Hi!

You have my Glider. VH-GFY listed as a Discus A when it's actually a Discus B.
Also, can you list it in Club Class for the Ingo Renner Cup?

Thanks

**Comment by moldhouse** [comment]
Hi, you can change the aircraft type in the flight settings, see [here](https://docs.weglide.org/docs/how_to/edit_flight/) on how to do that. According to the rules, only aircraft with an index of 106 or below can be flown in club class.
