### ISSUE TITLE
Ventus b WL missing

### ISSUE THREAD

**Issue by akalberer** [weglide/GliderList#29]
Hi

Ventus a/b 15m with Winglets (or Ventus 1 WL) is missing in the glider list or I was not able to find it.

Thanks for adding.

**Comment by moldhouse** [comment]
Can you provide more information for which gliders in the list we need to add the winglet option and maybe a reference to further information?
Ventus a 15m WL? Ventus b 15m WL? Ventus bT 15m WL? Ventus cM 15m WL?

**Comment by moldhouse** [comment]
@akalberer
