### ISSUE TITLE
Falscher Flugzeugtyp

### ISSUE THREAD

**Issue by thomhorz** [weglide/GliderList#31]
Hallo Weglide Team,
in meinen letzten zwei Flügen ist ein falscher Flugzeugtyp eingetragen.
Ich bin mit einer Stemme S10VT - S10S geflogen nicht mit einer SB10! D-KYTH s/n.: 11-106
Wie kann ich das ändern?
Vielen Dank für Eure Unterstützung!
Thomas Horz
thomas.horz@gmx.de

**Comment by moldhouse** [comment]
Hallo Thomas, solche Support Anfragen am Besten immer per Mail. Ich habe deine beiden Flüge geupdated. Das kannst du auch selber machen, hier ist die Anleitung: https://docs.weglide.org/how_to/edit_flight.html
