### ISSUE TITLE
Wrong aircraft type showing.

### ISSUE THREAD

**Issue by ls4top** [weglide/GliderList#36]
Wrong aircraft again; this time I did change the selection and the Nano has LS4 as the aircraft type.
Now what? May have to resort to OLC.

**Comment by moldhouse** [comment]
Hi, for support requests please refer to info@weglide.org in the future. Please also include a link to the flight in your support request.

[Here](https://docs.weglide.org/how_to/edit_flight.html) is some information on how to change the aircraft after uploading your flight. We always choose the latest aircraft type uploaded with the same logger, which may differ from the aircraft specified in the file. In some cases this may lead to undesired behavior, but in most cases, this works well.

**Comment by ls4top** [comment]
Thank you for your reply - I will try your suggestion soon.

Cheers for now.

George
________________________________

**Comment by ls4top** [comment]
Thank you again - success
