### ISSUE TITLE
Flügelfäche Antares 20 und 21 falsch hinterlegt

### ISSUE THREAD

**Issue by oliversoerensen** [weglide/GliderList#48]
Moin,

die Flügefläche einer Antares 21E = 20/21E ist 12,9m²  Weglide rechnet hier mit 21,9, das wäre ja eher eine 737 ;-) 
und der normalen 20E: 12,6 m² 

Viele Grüße 
Oliver

**Comment by moldhouse** [comment]
Moin Oliver, dank dir für den Hinweis. Ist korrigiert und die Daten werden in den nächsten Tagen importiert.
