### ISSUE TITLE
Incorrect glider type (user error)

### ISSUE THREAD

**Issue by nicolas6954** [weglide/GliderList#55]
Sorry, my last three flights are incorrect listed as in an Arcus-M.  They were flown in a Stemme S12.  I cannot figure out how to change this on WeGlide.  Perhaps the glider type is incorrect in my LX profile.  I will check tomorrow.

**Comment by flyingjoe** [comment]
Hi @nicolas6954, 

please send us an email, as we cannot monitor this channel for support requests and cannot figure out your WeGlide Profile from your github username ;)
