### ISSUE TITLE
Wrong Type for specific Glider

### ISSUE THREAD

**Issue by LeNinjaHD** [weglide/GliderList#70]
Our Discus CS is incorrectly labeled as a Discus a, however it should be a Discus b (with winglets)

**Comment by moldhouse** [comment]
Hi, this issue does not seem related to the GliderList. Please write an email to info@weglide.org describing the issue in more detail if you need help with this. 

If referring to the glider displayed with a flight, you can change it yourself, see [here](https://docs.weglide.org/how_to/edit_flight.html) for more information.

If you are referring to the glider name visible in the live tracking: We only provide a mapping from the ogn types to WeGlide ones. The ogn device database does not know a "discus cs", so we can not display a glider as discus cs in the live tracking. Please change your glider type in the ogn device database first.
